server:
    servlet:
        context-path: /api
    port: 8080


spring:
    datasource:
        url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console.enabled: true

springdoc:
    api-docs:
        path: /api-docs

documentation:
    openapi:
        info:
            prefix: ${API_PREFIX:APIrest}
            title: Rest API
            description: Rest API documentation
            version: 1.0
            contact:
                name: Prueba de promocion
                email: francisco.castaneda@globallogic.com